import { DEFAULT_CLUB_NAME, DEFAULT_SEASON } from '@/lib/app-config'
import { calculateAge } from '@/lib/utils'
import type {
  AttendanceSession,
  Club,
  Contribution,
  Match,
  Payment,
  Player,
  ReportRow,
  Suspension,
  Team,
  UserRole,
} from '@/lib/types'

export const currentClub: Club = {
  id: 'club-viitorul-onesti',
  name: DEFAULT_CLUB_NAME,
  cui: 'RO12345678',
  city: 'Onești',
  county: 'Bacău',
  logoUrl: '/fc-viitorul-onesti-logo.png',
  email: 'office@fcviitorulonesti.ro',
  phone: '+40 744 111 222',
  address: 'Str. Stadionului 12, Onești',
  website: 'https://fcviitorulonesti.ro',
  socialMedia: ['facebook.com/fcviitorulonesti', 'instagram.com/fcviitorulonesti'],
  subscriptionStatus: 'active',
  themeKey: 'viitorul-onesti',
}

export const currentUser = {
  id: 'demo-user-1',
  fullName: 'Raluca Munteanu',
  role: 'club_admin' as UserRole,
}

export const teams: Team[] = [
  {
    id: 'team-seniori',
    clubId: currentClub.id,
    name: `${currentClub.name} Seniori`,
    category: 'Seniori',
    competition: 'Liga 4',
    season: DEFAULT_SEASON,
    headCoach: 'Mihai Stoica',
    assistantCoach: 'Paul Cristea',
    teamManager: 'Andrei Enache',
  },
  {
    id: 'team-u17',
    clubId: currentClub.id,
    name: `${currentClub.name} U17`,
    category: 'U17',
    competition: 'Liga Elitelor U17',
    season: DEFAULT_SEASON,
    headCoach: 'Adrian Neagu',
    assistantCoach: 'Ionuț Barbu',
    teamManager: 'Mara Nistor',
  },
  {
    id: 'team-u13',
    clubId: currentClub.id,
    name: `${currentClub.name} U13`,
    category: 'U13',
    competition: 'AJF',
    season: DEFAULT_SEASON,
    headCoach: 'Sorin Avram',
    assistantCoach: 'Bogdan Petrescu',
    teamManager: 'Daniela Filip',
  },
]

export const players: Player[] = [
  {
    id: 'player-1',
    clubId: currentClub.id,
    teamId: 'team-seniori',
    firstName: 'Andrei',
    lastName: 'Pavel',
    dateOfBirth: '2001-08-14',
    position: 'Fundaș central',
    preferredFoot: 'drept',
    height: 186,
    weight: 81,
    phone: '+40 744 111 001',
    email: 'andrei.pavel@demo.ro',
    guardianName: 'N/A',
    guardianPhone: '-',
    guardianEmail: '-',
    registrationNumber: 'FRF-10045',
    status: 'activ',
    medicalNotes: 'Apt de joc.',
    coachNotes: 'Căpitan, foarte bun în duel aerian.',
    profileImageUrl: '',
    goals: 3,
    assists: 1,
    minutesPlayed: 1890,
  },
  {
    id: 'player-2',
    clubId: currentClub.id,
    teamId: 'team-u17',
    firstName: 'David',
    lastName: 'Sandu',
    dateOfBirth: '2009-04-02',
    position: 'Extremă',
    preferredFoot: 'ambele',
    height: 174,
    weight: 63,
    phone: '+40 744 111 002',
    email: 'david.sandu@demo.ro',
    guardianName: 'Cristina Sandu',
    guardianPhone: '+40 744 222 333',
    guardianEmail: 'cristina.sandu@demo.ro',
    registrationNumber: 'FRF-20117',
    status: 'activ',
    medicalNotes: 'Monitorizare gleznă stângă.',
    coachNotes: 'Explozie foarte bună pe spații largi.',
    profileImageUrl: '',
    goals: 14,
    assists: 8,
    minutesPlayed: 1420,
  },
  {
    id: 'player-3',
    clubId: currentClub.id,
    teamId: 'team-u13',
    firstName: 'Matei',
    lastName: 'Rotaru',
    dateOfBirth: '2013-10-21',
    position: 'Mijlocaș central',
    preferredFoot: 'stang',
    height: 151,
    weight: 42,
    phone: '+40 744 111 003',
    email: 'matei.rotaru@demo.ro',
    guardianName: 'Adrian Rotaru',
    guardianPhone: '+40 744 555 999',
    guardianEmail: 'adrian.rotaru@demo.ro',
    registrationNumber: 'AJF-40112',
    status: 'accidentat',
    medicalNotes: 'Recuperare după entorsă.',
    coachNotes: 'Joc foarte bun între linii.',
    profileImageUrl: '',
    goals: 7,
    assists: 11,
    minutesPlayed: 980,
  },
]

export const payments: Payment[] = [
  {
    id: 'payment-1',
    playerId: 'player-2',
    month: 'Aprilie',
    year: 2026,
    dueAmount: 350,
    paidAmount: 350,
    status: 'platit',
    paidAt: '2026-04-05',
    method: 'transfer_bancar',
    notes: 'Taxă achitată integral.',
  },
  {
    id: 'payment-2',
    playerId: 'player-3',
    month: 'Aprilie',
    year: 2026,
    dueAmount: 300,
    paidAmount: 150,
    status: 'partial',
    paidAt: '2026-04-12',
    method: 'cash',
    notes: 'Rest până la final de lună.',
  },
  {
    id: 'payment-3',
    playerId: 'player-1',
    month: 'Aprilie',
    year: 2026,
    dueAmount: 0,
    paidAmount: 0,
    status: 'scutit',
    paidAt: null,
    method: 'card',
    notes: 'Contract seniori.',
  },
]

export const contributions: Contribution[] = [
  {
    id: 'contribution-1',
    clubId: currentClub.id,
    contributorName: 'Maria Iftime',
    contributorEmail: 'maria.iftime@demo.ro',
    contributorPhone: '+40 744 888 001',
    type: 'donatie',
    amount: 500,
    status: 'paid',
    source: 'online',
    provider: 'stripe',
    checkoutUrl: 'https://pay.demo.ro/fcviitorulonesti/donatie-500',
    externalCheckoutId: 'cs_demo_paid_001',
    sponsorCompany: '',
    notes: 'Susținere pentru grupa U13.',
    paidAt: '2026-04-18',
  },
  {
    id: 'contribution-2',
    clubId: currentClub.id,
    contributorName: 'Construct Invest',
    contributorEmail: 'office@constructinvest.ro',
    contributorPhone: '+40 744 888 002',
    type: 'sponsorizare',
    amount: 3500,
    status: 'pending',
    source: 'online',
    provider: 'stripe',
    checkoutUrl: 'https://pay.demo.ro/fcviitorulonesti/sponsor-construct-invest',
    externalCheckoutId: 'cs_demo_pending_002',
    sponsorCompany: 'Construct Invest',
    notes: 'Pachet panotaj meciuri seniori.',
    paidAt: null,
  },
]

export const attendanceSessions: AttendanceSession[] = [
  {
    id: 'att-1',
    teamId: 'team-seniori',
    date: '2026-04-28',
    hour: '18:00',
    location: 'Baza Sportivă Onești',
    type: 'antrenament',
    attendanceRate: 95,
  },
  {
    id: 'att-2',
    teamId: 'team-u17',
    date: '2026-04-29',
    hour: '17:30',
    location: 'Teren Sintetic 2',
    type: 'sedinta_video',
    attendanceRate: 88,
  },
]

export const matches: Match[] = [
  {
    id: 'match-1',
    teamId: 'team-seniori',
    competition: 'Liga 4',
    round: 'Etapa 24',
    opponent: 'CSM Moinești',
    venueType: 'acasa',
    date: '2026-05-03',
    hour: '18:00',
    location: 'Stadionul Municipal Onești',
    teamScore: null,
    opponentScore: null,
    status: 'programat',
    notes: 'Necesare aprobări pentru branding parteneri.',
  },
  {
    id: 'match-2',
    teamId: 'team-u17',
    competition: 'Liga Elitelor U17',
    round: 'Etapa 19',
    opponent: 'LPS Roman',
    venueType: 'deplasare',
    date: '2026-04-26',
    hour: '12:00',
    location: 'Roman',
    teamScore: 2,
    opponentScore: 1,
    status: 'jucat',
    notes: 'Victorie după gol în minutul 82.',
  },
]

export const suspensions: Suspension[] = [
  {
    id: 'suspension-1',
    playerId: 'player-1',
    matchId: 'match-1',
    reason: 'cumul_galbene',
    rounds: 1,
    remainingRounds: 1,
    startDate: '2026-05-03',
    status: 'activa',
  },
]

export const reports: ReportRow[] = [
  {
    title: 'Raport jucător',
    subtitle: 'Fișă individuală completă, minute și observații.',
    metric: '148 jucători',
  },
  {
    title: 'Raport taxe',
    subtitle: 'Situație încasări, restanțe și export contabil.',
    metric: '18.450 RON',
  },
  {
    title: 'Raport statistici sezon',
    subtitle: 'Goluri, assisturi, minute, cartonașe.',
    metric: '3 echipe active',
  },
]

export const dashboardStats = {
  totalPlayers: players.length,
  totalTeams: teams.length,
  outstandingPayments: payments
    .filter((payment) => payment.status === 'partial' || payment.status === 'restant')
    .reduce((total, payment) => total + (payment.dueAmount - payment.paidAmount), 0),
  nextMatches: matches.filter((match) => match.status === 'programat').length,
  suspendedPlayers: suspensions.filter((item) => item.status === 'activa').length,
  topScorer: players.reduce((top, player) => (player.goals > top.goals ? player : top), players[0]),
}

export const playerTable = players.map((player) => {
  const team = teams.find((entry) => entry.id === player.teamId)

  return {
    id: player.id,
    name: `${player.firstName} ${player.lastName}`,
    team: team?.name ?? '-',
    age: calculateAge(player.dateOfBirth),
    position: player.position,
    status: player.status,
    goals: player.goals,
  }
})
