export type ProfileKey =
  | 'athlete'
  | 'entrepreneur'
  | 'artist'
  | 'student'
  | 'employee'
  | 'job-seeker'

export type DailyEntry = {
  message: string
  task: string
}

export type ProfileOption = {
  key: ProfileKey
  label: string
  description: string
}

export const PROFILE_OPTIONS: ProfileOption[] = [
  { key: 'athlete', label: 'Athlete', description: 'Build disciplined training and recovery habits.' },
  {
    key: 'entrepreneur',
    label: 'Entrepreneur',
    description: 'Create revenue-moving momentum with daily focused actions.',
  },
  { key: 'artist', label: 'Artist', description: 'Finish more creative reps and publish more often.' },
  { key: 'student', label: 'Student', description: 'Study with structure and reduce avoidable drift.' },
  { key: 'employee', label: 'Employee', description: 'Advance your work quality, output, and visibility.' },
  {
    key: 'job-seeker',
    label: 'Unemployed / Job seeker',
    description: 'Turn the job search into a repeatable daily system.',
  },
]

function createDays(items: DailyEntry[]) {
  return items
}

export const profileContent: Record<ProfileKey, DailyEntry[]> = {
  athlete: createDays([
    { message: 'Win the first rep before excuses wake up.', task: 'Do a 10-minute mobility circuit for hips, ankles, and shoulders before breakfast.' },
    { message: 'Film reveals what emotion hides.', task: 'Record five reps of one key movement and note one technical fix.' },
    { message: 'Recovery is training with quieter clothes.', task: 'Spend 12 minutes foam rolling your tightest two muscle groups.' },
    { message: 'Discipline shows in the boring details.', task: 'Prep tomorrow’s training bag, water, and post-session snack tonight.' },
    { message: 'Your engine improves when you measure it.', task: 'Walk briskly for 15 minutes and track breathing recovery after minute fifteen.' },
    { message: 'Great athletes revisit fundamentals relentlessly.', task: 'Perform 50 slow bodyweight reps of a sport-specific basic movement.' },
    { message: 'Your weak side deserves equal attention.', task: 'Practice 10 minutes using only your weaker hand, foot, or stance.' },
    { message: 'Consistency grows when friction shrinks.', task: 'Lay out clothes and set one exact training time for tomorrow.' },
    { message: 'Fueling late is progress delayed.', task: 'Build one protein-first meal and eat it without screens.' },
    { message: 'Breathing control sharpens late-game control.', task: 'Complete six rounds of nasal breathing: inhale four, exhale six.' },
    { message: 'Speed starts with clean mechanics.', task: 'Do eight 10-second acceleration starts, resting fully between each.' },
    { message: 'The body follows the quality of attention.', task: 'Spend 10 minutes on balance work using one leg and eyes forward.' },
    { message: 'A real competitor reviews losses honestly.', task: 'Write three mistakes from your last session and one correction each.' },
    { message: 'Small recovery choices protect future output.', task: 'Take a 15-minute walk immediately after your hardest meal today.' },
    { message: 'Explosiveness fades when stiffness wins.', task: 'Do 12 minutes of dynamic stretching focused on hamstrings and calves.' },
    { message: 'If grip slips, performance leaks.', task: 'Complete three rounds of 30-second dead hangs or towel holds.' },
    { message: 'Elite minds rehearse before pressure arrives.', task: 'Visualize five perfect reps of tomorrow’s hardest movement with closed eyes.' },
    { message: 'Your calendar exposes your priorities.', task: 'Block your next three training windows in your phone right now.' },
    { message: 'Durability is a competitive advantage.', task: 'Perform two rounds of glute activation and core bracing drills.' },
    { message: 'Focus beats volume when time is tight.', task: 'Do a 15-minute skill session on your most unreliable technique.' },
    { message: 'Sleep preparation starts before the bed.', task: 'Cut screens 20 minutes early and stretch for eight quiet minutes.' },
    { message: 'Confident athletes track evidence, not feelings.', task: 'Log today’s energy, soreness, and confidence from one to five.' },
    { message: 'Conditioning improves when pacing is honest.', task: 'Complete 10 minutes of intervals: 40 seconds hard, 20 seconds easy.' },
    { message: 'Stronger posture creates cleaner movement.', task: 'Do three rounds of rows, band pull-aparts, or scap squeezes.' },
    { message: 'Delayed maintenance becomes forced rest.', task: 'Ice, elevate, or compress any nagging area for 10 minutes.' },
    { message: 'Athletes who learn faster improve longer.', task: 'Watch one short clip from a top performer in your position.' },
    { message: 'The next level starts with sharper standards.', task: 'Clean up your training notes and rewrite one clearer performance target.' },
    { message: 'Fast minds still need stillness.', task: 'Spend seven minutes breathing quietly and releasing jaw and shoulder tension.' },
    { message: 'Preparation makes intensity usable.', task: 'Pack tomorrow’s nutrition, water, and recovery items before sleeping.' },
    { message: 'Thirty days matter when today is handled.', task: 'Repeat your best drill from this month for 15 deliberate minutes.' },
  ]),
  entrepreneur: createDays([
    { message: 'Revenue loves direct action, not vague momentum.', task: 'Send one concise offer message to a warm prospect today.' },
    { message: 'Clarity compounds faster than hustle theater.', task: 'Write your single most important business outcome for this week.' },
    { message: 'Sales improve when friction is removed first.', task: 'Shorten one step in your inquiry, booking, or checkout process.' },
    { message: 'Founders drift when numbers stay fuzzy.', task: 'Review yesterday’s revenue, leads, and cash balance for 10 minutes.' },
    { message: 'Your best channel deserves focused reps.', task: 'Create and publish one practical post where buyers already watch you.' },
    { message: 'A weak offer creates exhausting marketing.', task: 'Rewrite your main offer in one sentence using outcome, speed, and audience.' },
    { message: 'Objections lose power when documented early.', task: 'List the top three objections prospects repeat and draft one answer each.' },
    { message: 'Speed beats perfection in customer follow-up.', task: 'Reply to every open lead message within 15 minutes total.' },
    { message: 'A founder’s calendar shows business truth.', task: 'Delete one low-value task from tomorrow and replace it with outreach.' },
    { message: 'One clean system beats scattered apps.', task: 'Organize active leads into one simple list with next action dates.' },
    { message: 'The market rewards specificity quickly.', task: 'Narrow one landing page headline to a single customer type.' },
    { message: 'Cash confidence comes from small reviews.', task: 'Check subscriptions, tools, or expenses and cancel one nonessential cost.' },
    { message: 'Momentum grows when asks are explicit.', task: 'Make one direct referral request to a satisfied customer.' },
    { message: 'Founders hide from the phone too often.', task: 'Record a 60-second voice note explaining your offer clearly.' },
    { message: 'Better questions create better customer data.', task: 'Ask one customer why they chose you instead of waiting.' },
    { message: 'Decision fatigue fades with standard offers.', task: 'Turn one custom service into a fixed-scope package draft.' },
    { message: 'Small visibility beats long silent preparation.', task: 'Comment thoughtfully on five posts from people in your market.' },
    { message: 'Growth starts where confusion ends.', task: 'Identify the one metric that proves this month is working.' },
    { message: 'Proof closes deals faster than passion.', task: 'Collect one testimonial, screenshot, or result and store it neatly.' },
    { message: 'Your follow-up sequence is hidden revenue.', task: 'Draft a short follow-up message for leads who went quiet.' },
    { message: 'Execution loves a smaller priority list.', task: 'Choose one task to finish before noon and mute everything else.' },
    { message: 'Offer delivery shapes future retention.', task: 'Improve one client handoff or onboarding message for clarity.' },
    { message: 'Founders need recovery to think sharply.', task: 'Take a 15-minute walk without podcasts and solve one business bottleneck.' },
    { message: 'The easiest sale is to the right fit.', task: 'Write two signs someone is an ideal client for you.' },
    { message: 'Attention follows repetition, not bursts.', task: 'Schedule tomorrow’s most important piece of outreach right now.' },
    { message: 'Every bottleneck deserves a named owner.', task: 'Choose one recurring issue and write the next exact fix step.' },
    { message: 'Sharpen the pitch before the meeting starts.', task: 'Practice your offer out loud three times without filler words.' },
    { message: 'Simple reporting creates calmer decisions.', task: 'Write a five-line weekly summary: wins, misses, leads, cash, next move.' },
    { message: 'The founder who asks clearly gets answers faster.', task: 'Reach out to one peer or mentor with one specific question.' },
    { message: 'Close the month with evidence, not vibes.', task: 'Review the strongest task from this month and repeat it today.' },
  ]),
  artist: createDays([
    { message: 'Finished work teaches faster than private doubt.', task: 'Create one rough piece for 15 minutes without editing mid-way.' },
    { message: 'Creative confidence grows from visible reps.', task: 'Fill one page with 12 tiny concept sketches or lines.' },
    { message: 'Your voice appears after enough output.', task: 'Write or record for 10 minutes in a style that feels natural.' },
    { message: 'Reference study sharpens instinct quickly.', task: 'Analyze one admired piece and list three choices you notice.' },
    { message: 'A small daily ritual reduces resistance.', task: 'Prepare your workspace and begin one timer-based session today.' },
    { message: 'Artists improve when drafts stay moving.', task: 'Take one unfinished piece and push it to a cleaner draft.' },
    { message: 'Creative blocks hate tiny deadlines.', task: 'Set a 12-minute timer and make something around one simple theme.' },
    { message: 'Better taste comes from active observation.', task: 'Photograph or save five visual references connected to your current project.' },
    { message: 'Editing is easier after raw material exists.', task: 'Generate three alternative titles, captions, or compositions for one idea.' },
    { message: 'Momentum breaks when tools stay messy.', task: 'Organize your top-used brushes, files, instruments, or materials for 10 minutes.' },
    { message: 'Publishing is part of the craft.', task: 'Share one work-in-progress privately or publicly with one sentence of context.' },
    { message: 'Creative range expands through constraints.', task: 'Make one piece using only two colors, chords, words, or textures.' },
    { message: 'Taste sharpens when comparisons are specific.', task: 'Place your piece beside a strong reference and note one upgrade.' },
    { message: 'Art careers move through consistent exposure.', task: 'Send one portfolio, track, or sample to one relevant person.' },
    { message: 'Messy archives hide good ideas.', task: 'Rename and sort your latest five files so you can find them fast.' },
    { message: 'One honest critique saves weeks.', task: 'Ask one trusted person for one specific feedback point on your work.' },
    { message: 'Creative stamina grows like physical stamina.', task: 'Do a 20-minute uninterrupted making session with phone on airplane mode.' },
    { message: 'Repetition can become style if noticed.', task: 'Review your last three pieces and identify one recurring strength.' },
    { message: 'Professional artists document the process.', task: 'Take three progress photos or notes from today’s session.' },
    { message: 'A small release beats a perfect draft folder.', task: 'Finish and post one tiny piece, even if it feels modest.' },
    { message: 'Skill improves when one weakness gets targeted.', task: 'Practice only your weakest technique for 15 focused minutes.' },
    { message: 'Your audience needs consistency more than volume.', task: 'Plan the next two pieces you can realistically finish this week.' },
    { message: 'Study without making becomes disguised delay.', task: 'After five minutes of research, create one response inspired by it.' },
    { message: 'Energy matters; protect it with boundaries.', task: 'Remove one distraction from your workspace before creating tonight.' },
    { message: 'A stronger process beats waiting for mood.', task: 'Start at the same time today you created yesterday.' },
    { message: 'Creative identity is built through choices.', task: 'Write five words describing how you want your work to feel.' },
    { message: 'Drafts improve when distance is brief.', task: 'Revisit yesterday’s piece and make only three intentional edits.' },
    { message: 'Professionalism includes simple follow-through.', task: 'Answer one pending email, DM, or inquiry about your work.' },
    { message: 'Quiet focus often unlocks the cleanest work.', task: 'Create for 15 minutes with no music, no tabs, no interruptions.' },
    { message: 'The month counts when the page is touched.', task: 'Return to your best idea from this month and advance it.' },
  ]),
  student: createDays([
    { message: 'A short focused block beats fake long hours.', task: 'Study one subject for 15 minutes with your phone in another room.' },
    { message: 'Confusion shrinks when you test recall.', task: 'Close your notes and write everything you remember on one topic.' },
    { message: 'Start with the hardest page, not the easiest.', task: 'Spend 10 minutes on the chapter or problem you keep avoiding.' },
    { message: 'Clean notes save time later.', task: 'Rewrite one messy page of notes into five clear bullet points.' },
    { message: 'Planning lowers panic before exams do.', task: 'List this week’s deadlines and circle the closest one.' },
    { message: 'Active practice wins over passive rereading.', task: 'Solve three problems or answer three questions without looking first.' },
    { message: 'Memory improves when review gets scheduled.', task: 'Set one reminder to revisit today’s topic within 48 hours.' },
    { message: 'Your desk can quietly drain attention.', task: 'Spend eight minutes clearing your study surface completely.' },
    { message: 'Better questions create faster progress.', task: 'Write one question to ask a classmate, teacher, or forum today.' },
    { message: 'Exam confidence is built in small reps.', task: 'Do one timed 10-minute mini-test on a current subject.' },
    { message: 'Reading without notes is slippery memory.', task: 'Summarize one page or concept in your own words.' },
    { message: 'One missing foundation slows every advanced task.', task: 'Review one basic formula, rule, or definition you keep forgetting.' },
    { message: 'Good students notice patterns in mistakes.', task: 'Look at two wrong answers and write why each happened.' },
    { message: 'Energy management is part of studying well.', task: 'Take a brisk 10-minute walk before your next study block.' },
    { message: 'A smaller next step beats overwhelm.', task: 'Break one large assignment into three actions you can name clearly.' },
    { message: 'Your future self needs organized materials.', task: 'Sort one folder, notebook section, or digital class workspace.' },
    { message: 'Repetition works better when spaced intentionally.', task: 'Review yesterday’s topic for 10 minutes before starting anything new.' },
    { message: 'Silence is a productivity tool.', task: 'Use one 15-minute no-music, no-chat, no-tab-switch study sprint.' },
    { message: 'Explaining proves understanding honestly.', task: 'Teach one concept out loud as if helping a younger student.' },
    { message: 'Grades improve when feedback gets used.', task: 'Review one teacher comment and apply it to a small revision.' },
    { message: 'Sleep is part of retention, not a reward.', task: 'Stop studying 15 minutes earlier and prep for sleep calmly.' },
    { message: 'Momentum comes from visible completion.', task: 'Finish one tiny overdue task you can complete today.' },
    { message: 'Strong revision starts with priorities.', task: 'Rank your subjects by urgency and difficulty in one note.' },
    { message: 'Phone friction protects deep work.', task: 'Move distracting apps off your home screen for today.' },
    { message: 'Stress drops when you face the exact problem.', task: 'Open the assignment portal and read every instruction carefully once.' },
    { message: 'Consistency beats cram cycles every time.', task: 'Schedule tomorrow’s study block with a start time and subject.' },
    { message: 'Attention returns when your body resets.', task: 'Stretch neck, back, and wrists for seven minutes between blocks.' },
    { message: 'A student with a review loop improves faster.', task: 'Write what worked and failed in today’s study session.' },
    { message: 'Finish the day by reducing tomorrow’s friction.', task: 'Set out the materials you need for your first study block tomorrow.' },
    { message: 'Thirty days of reps turn stress into structure.', task: 'Repeat the study method that helped you most this month.' },
  ]),
  employee: createDays([
    { message: 'Strong workdays start before inbox chaos.', task: 'Choose the one task that matters most before opening email.' },
    { message: 'Visibility grows when updates stay crisp.', task: 'Send one concise progress update to a manager or teammate.' },
    { message: 'Busy is not the same as useful.', task: 'Delete or defer one meeting that does not need you.' },
    { message: 'Great employees document decisions clearly.', task: 'Write a short summary after one conversation or meeting today.' },
    { message: 'Your value rises when problems are clarified.', task: 'Turn one vague task into a checklist with next actions.' },
    { message: 'Small follow-through builds trust fast.', task: 'Close one lingering work loop that has been open all week.' },
    { message: 'Calm operators reduce avoidable back-and-forth.', task: 'Ask one clarifying question before starting a task with ambiguity.' },
    { message: 'The calendar can protect real output.', task: 'Block 20 minutes for focused work with notifications off.' },
    { message: 'Professional growth needs evidence, not hope.', task: 'Write down one measurable win from this week.' },
    { message: 'A cleaner handoff saves everyone time.', task: 'Improve one status note, ticket, or document so others need fewer questions.' },
    { message: 'Strong communication removes uncertainty early.', task: 'Reply to one important message with a clear yes, no, or next step.' },
    { message: 'You get faster by reducing repeated setup.', task: 'Create one reusable template for a common message or task.' },
    { message: 'Reliable people surface risks before deadlines.', task: 'Identify one blocker and communicate it today with a proposed fix.' },
    { message: 'Energy management changes output quality.', task: 'Take a 10-minute screen break before your next focused task.' },
    { message: 'Better notes create better execution later.', task: 'Capture the three decisions from your last meeting in one place.' },
    { message: 'Career momentum comes from owned improvement.', task: 'Pick one skill gap and spend 15 minutes learning a relevant tactic.' },
    { message: 'A tidy workspace reduces hidden friction.', task: 'Clean your desktop, downloads, or physical workspace for 10 minutes.' },
    { message: 'The best colleagues make decisions easier.', task: 'Prepare two options and a recommendation for one pending choice.' },
    { message: 'Your manager should not guess your progress.', task: 'Draft a brief update covering done, next, and blocked.' },
    { message: 'Fewer tabs, better thinking.', task: 'Close every tab unrelated to your next work block.' },
    { message: 'Skillful employees protect deep work windows.', task: 'Do one 15-minute uninterrupted session on your hardest task.' },
    { message: 'Trust grows when promises are realistic.', task: 'Renegotiate one deadline early if you know it is slipping.' },
    { message: 'Small systems reduce recurring mistakes.', task: 'Write a checklist for one process you often repeat.' },
    { message: 'Influence increases when you notice problems early.', task: 'Suggest one practical improvement to a team workflow.' },
    { message: 'Work stress drops when priorities are visible.', task: 'List today’s top three tasks and finish the first one fully.' },
    { message: 'Promotion-ready people keep proof.', task: 'Save one result, metric, or compliment in a brag document.' },
    { message: 'Attention is a workplace asset.', task: 'Mute nonessential chat channels for one focused work block.' },
    { message: 'Helpful people become indispensable faster.', task: 'Unblock one teammate with a short useful answer or resource.' },
    { message: 'A steady finish beats a scattered sprint.', task: 'End the day by preparing tomorrow’s first task and materials.' },
    { message: 'Thirty days of execution changes reputation.', task: 'Repeat the work habit that improved your output most this month.' },
  ]),
  'job-seeker': createDays([
    { message: 'Job searching works better as a system.', task: 'Update the headline of your CV or LinkedIn in one clear sentence.' },
    { message: 'Momentum starts with visible opportunities.', task: 'Save three realistic job postings that fit your current level.' },
    { message: 'Generic applications disappear quietly.', task: 'Tailor your CV bullet points for one specific role today.' },
    { message: 'A focused search beats random clicking.', task: 'Choose one job title and one location to target this week.' },
    { message: 'Confidence grows from practiced stories.', task: 'Write one 60-second answer to “Tell me about yourself.”' },
    { message: 'Networking is easier when the ask is simple.', task: 'Message one former colleague or friend with a clear update.' },
    { message: 'Your profile should show results quickly.', task: 'Add one measurable achievement to your resume or profile.' },
    { message: 'Consistency beats occasional application marathons.', task: 'Submit one complete application with no skipped fields.' },
    { message: 'A better tracker creates calmer follow-up.', task: 'Start one simple list for jobs, dates, and next actions.' },
    { message: 'Interviews reward prepared examples.', task: 'Write one STAR story about solving a problem at work.' },
    { message: 'Weak openings lose recruiter attention fast.', task: 'Rewrite your resume summary in plain, direct language.' },
    { message: 'A sharper search starts with role clarity.', task: 'List the top three roles you are actually willing to take.' },
    { message: 'Silence is normal; follow-up is strategic.', task: 'Send one polite follow-up for a role you already applied to.' },
    { message: 'Better applications come from employer research.', task: 'Read one company’s about page and note two relevant details.' },
    { message: 'Your references should not be last-minute.', task: 'Check in with one potential reference and confirm they are willing.' },
    { message: 'Preparation lowers interview anxiety.', task: 'Practice three common interview questions out loud for 10 minutes.' },
    { message: 'Job seekers need proof, not only duties.', task: 'Turn one past responsibility into an outcome-driven resume bullet.' },
    { message: 'Small outreach beats waiting passively.', task: 'Connect with one recruiter or hiring manager in your field.' },
    { message: 'A clear portfolio beats extra explanation.', task: 'Organize one sample, project, or case study you can share quickly.' },
    { message: 'Follow-through signals professionalism early.', task: 'Reply to every active hiring conversation before the day ends.' },
    { message: 'Your search deserves protected time.', task: 'Block tomorrow’s 20-minute application or outreach window now.' },
    { message: 'Interview strength comes from honest reflection.', task: 'Write two lessons from your last rejection or missed opportunity.' },
    { message: 'Applications improve when friction drops.', task: 'Create a plain-text document with your common answers ready to paste.' },
    { message: 'Energy matters during long searches.', task: 'Take a 15-minute walk before your next application session.' },
    { message: 'Your online presence should match your target.', task: 'Remove one outdated or distracting item from your public profile.' },
    { message: 'A warm intro can beat ten cold forms.', task: 'Ask one contact if they know anyone hiring for your target role.' },
    { message: 'Prepared candidates close faster.', task: 'Write three questions you can ask at the end of an interview.' },
    { message: 'One clean document saves repeated effort.', task: 'Create a master resume with your best bullet points organized by role.' },
    { message: 'Keep momentum by seeing what is working.', task: 'Review which applications got responses and spot one pattern.' },
    { message: 'Thirty days count when effort stays directed.', task: 'Repeat the outreach or application tactic that worked best this month.' },
  ]),
}
